import 'package:home/models/anime_model.dart';

class AnimeDataSource {
  List<Anime> getAnime() {
    return [
      Anime(
        id: 1,
        title: 'Kimetsu No Yaiba',
        rating: 9.2,
        image: 'https://i2.wp.com/komikstation.co/wp-content/uploads/2018/01/Kimetsu-no-Yaiba.png',
        genre: ['Action', 'Adventure', 'Drama'],
        chapter: 205,
        likes: 980,
        view: 1230,
        status: 'Completed',
        sinopsis: 'Tanjiro merupakan anak sulung dari keluarga yang kehilangan ayahnya...',
        author: 'GOTOUGE Koyoharu',
      ),
      Anime(
        id: 2,
        title: 'One Piece',
        rating: 9.7,
        image: 'https://i1.wp.com/komikstation.co/wp-content/uploads/2017/11/One-Piece-Vol-106.png',
        genre: ['Action', 'Adventure', 'Comedy', 'Fantasy', 'Martial Arts', 'Mystery', 'Shounen', 'Supernatural'],
        chapter: 1211,
        likes: 1500,
        view: 1470,
        status: 'Ongoing',
        sinopsis: 'Bercerita tentang seorang laki-laki bernama Monkey D. Luffy...',
        author: 'Oda Eichiro',
      ),
      Anime(
        id: 3,
        title: 'Ruri Dragon',
        rating: 8.5,
        image: 'https://i2.wp.com/komikstation.co/wp-content/uploads/2021/02/Ruri-Dragon-Vol-2.jpg',
        genre: ['Action', 'Comedy', 'School Life', 'Shounen', 'Supernatural'],
        chapter: 31,
        likes: 650,
        view: 980,
        status: 'Ongoing',
        sinopsis: 'Pembunuh bayaran Juzo Ogami dikenal sebagai legenda di dunia hitam...',
        author: 'FUJIMAKI Tadatoshi',
      ),
      Anime(
        id: 4,
        title: 'Kill Blue',
        rating: 8.3,
        image: 'https://i0.wp.com/komikstation.co/wp-content/uploads/2023/04/Kill-Blue-Vol-8.jpg',
        genre: ['Action', 'Comedy', 'School Life', 'Shounen', 'Supernatural'],
        chapter: 93,
        likes: 720,
        view: 1110,
        status: 'Ongoing',
        sinopsis: 'Pembunuh bayaran Juzo Ogami dikenal sebagai legenda di dunia hitam...',
        author: 'FUJIMAKI Tadatoshi',
      ),
      Anime(
        id: 5,
        title: 'Komi-san wa Komyushou Desu',
        rating: 8.8,
        image: 'https://i0.wp.com/komikstation.co/wp-content/uploads/2018/02/Komi-san-wa-Komyushou-Desu.jpg',
        genre: ['Comedy', 'Romance', 'School Life', 'Shounen', 'Slice Of Life'],
        chapter: 448,
        likes: 1100,
        view: 1420,
        status: 'Ongoing',
        sinopsis: 'Komi-san adalah gadis cantik dan mengagumkan...',
        author: 'Oda Tomohito',
      ),
      Anime(
        id: 6,
        title: 'Plunderer',
        rating: 8.4,
        image: 'https://i0.wp.com/komikstation.co/wp-content/uploads/2018/04/14405.jpg',
        genre: ['Action', 'Adventure', 'Comedy', 'Drama', 'Ecchi', 'Romance', 'Seinen', 'Supernatural'],
        chapter: 82,
        likes: 780,
        view: 1010,
        status: 'Ongoing',
        sinopsis: 'Tahun 305 Kalender Alcian, dan dunia saat ini dikendalikan oleh "Numbers"...',
        author: 'Minazuki Zuu',
      ),
      Anime(
        id: 7,
        title: 'Nidome no Jinsei wo Isekai de',
        rating: 8.1,
        image: 'https://i0.wp.com/komikstation.co/wp-content/uploads/2018/02/Nidome-no-Jinsei-wo-Isekai-de.jpg',
        genre: ['Action', 'Adventure', 'Comedy', 'Drama', 'Ecchi', 'Fantasy', 'Harem', 'Isekai', 'Romance', 'Shounen'],
        chapter: 49,
        likes: 690,
        view: 1085,
        status: 'Ongoing',
        sinopsis: 'Kunugi Renya merupakan sosok yang sudah tiada di usia tuanya...',
        author: 'Main',
      ),
      Anime(
        id: 8,
        title: 'Sekai Ni Hitori, Zenzokusei Mahou no Tsukaite',
        rating: 8.0,
        image: 'https://i3.wp.com/komikstation.co/wp-content/uploads/2023/02/Sekai-ni-Hitori-Zenzokusei-Mahou-no-Tsukaite-Vol-1.jpg',
        genre: ['Action', 'Adventure', 'Fantasy', 'Seinen'],
        chapter: 38,
        likes: 540,
        view: 970,
        status: 'Ongoing',
        sinopsis: 'Setelah kecelakaan lalu lintas, Zenichi Kiyama bereinkarnasi...',
        author: 'Katanakaji',
      ),
      Anime(
        id: 9,
        title: 'Isekai de Slow Life wo (Ganbou)',
        rating: 7.9,
        image: 'https://i1.wp.com/komikstation.co/wp-content/uploads/2022/01/Isekai-de-Slow-Life-wo-Ganbou.jpg',
        genre: ['Action', 'Adventure', 'Ecchi', 'Harem', 'Isekai', 'Shounen'],
        chapter: 51,
        likes: 620,
        view: 890,
        status: 'Ongoing',
        sinopsis: 'Dengan kehendak sang dewi, Itsuki shinomiya diberi hak istimewa...',
        author: 'Shige',
      ),
      Anime(
        id: 10,
        title: 'Exorcist wo Otosenai',
        rating: 8.2,
        image: 'https://i2.wp.com/komikstation.co/wp-content/uploads/2022/07/Exorcist-wo-Otosenai.jpg',
        genre: ['Comedy', 'Romance', 'Shounen', 'Supernatural'],
        chapter: 44,
        likes: 710,
        view: 1050,
        status: 'Ongoing',
        sinopsis: 'Sebagai pengusir setan terkuat, seorang anak laki-laki yang dipilih oleh Tuhan...',
        author: 'Arima Aruma',
      ),
    ];
  }
}