import 'package:home/models/anime_model.dart';

class AnimeDataSource {
  List<Anime> getAnime() {
    return [
      Anime(
        id: 1,
        title: "Kimetsu No Yaiba",
        image:
            "https://i2.wp.com/komikstation.co/wp-content/uploads/2018/01/Kimetsu-no-Yaiba.png",
        chapter: 205,
        status: "Completed",
        release: "2016",
        author: "GOTOUGE Koyoharu",
        genre: ["Action", "Adventure", "Drama"],
        sinopsis:
            "Tanjiro merupakan anak sulung dari keluarga yang kehilangan ayahnya...",
        rating: 4.8,
        likes: 1480,
        view: 1450,
      ),
      Anime(
        id: 2,
        title: "One Piece",
        image:
            "https://i1.wp.com/komikstation.co/wp-content/uploads/2017/11/One-Piece-Vol-106.png",
        chapter: 1211,
        status: "Ongoing",
        sinopsis:
            "Bercerita tentang seorang laki-laki bernama Monkey D. Luffy...",
        release: "1997",
        genre: [
          "Action",
          "Adventure",
          "Comedy",
          "Fantasy",
          "Martial Arts",
          "Mystery",
          "Shounen",
          "Supernatural",
        ],
        author: "Oda Eichiro",
        rating: 4.9,
        likes: 1495,
        view: 1500,
      ),
      Anime(
        id: 3,
        title: "Ruri Dragon",
        image:
            "https://i2.wp.com/komikstation.co/wp-content/uploads/2021/02/Ruri-Dragon-Vol-2.jpg",
        chapter: 31,
        status: "Ongoing",
        sinopsis:
            "Pembunuh bayaran Juzo Ogami dikenal sebagai legenda di dunia hitam...",
        release: "2022",
        genre: ["Action", "Comedy", "School Life", "Shounen", "Supernatural"],
        author: "FUJIMAKI Tadatoshi",
        rating: 4.3,
        likes: 870,
        view: 920,
      ),
      Anime(
        id: 4,
        title: "Kill Blue",
        image:
            "https://i0.wp.com/komikstation.co/wp-content/uploads/2023/04/Kill-Blue-Vol-8.jpg",
        chapter: 93,
        status: "Ongoing",
        sinopsis:
            "Pembunuh bayaran Juzo Ogami dikenal sebagai legenda di dunia hitam...",
        release: "2023",
        genre: ["Action", "Comedy", "School Life", "Shounen", "Supernatural"],
        author: "FUJIMAKI Tadatoshi",
        rating: 4.2,
        likes: 820,
        view: 890,
      ),
      Anime(
        id: 5,
        title: "Komi-san wa Komyushou Desu",
        image:
            "https://i0.wp.com/komikstation.co/wp-content/uploads/2018/02/Komi-san-wa-Komyushou-Desu.jpg",
        chapter: 448,
        status: "Ongoing",
        sinopsis:
            "Komi-san adalah gadis cantik dan mengagumkan yang tak seorang pun bisa melepaskan pandangan kepadanya...",
        release: "2016",
        genre: ["Comedy", "Romance", "School Life", "Shounen", "Slice Of Life"],
        author: "Oda Tomohito",
        rating: 4.7,
        likes: 1320,
        view: 1280,
      ),
      Anime(
        id: 6,
        title: "Gachi Koi Maou-sama",
        image:
            "https://i0.wp.com/komikstation.co/wp-content/uploads/2023/04/Gachi-Koi-Maou-sama.jpg",
        chapter: 23,
        status: "Ongoing",
        sinopsis:
            "Seorang pahlawan bertugas untuk mengalahkan Raja Iblis demi perdamaian dunia...",
        release: "2023",
        genre: ["Comedy", "Fantasy", "Romance", "Seinen"],
        author: "Moriya Haru",
        rating: 4.1,
        likes: 780,
        view: 810,
      ),
      Anime(
        id: 7,
        title: "Taiyou no Ie",
        image:
            "https://i1.wp.com/komikstation.co/wp-content/uploads/2018/04/Taiyou-no-Ie-Cover.jpg",
        chapter: 40,
        status: "Ongoing",
        sinopsis:
            "Waktu itu, sebuah rumah yang penuh dengan sihir - tempat dimana kamu yang menangispun bisa tersenyum...",
        release: "2018",
        genre: [
          "Comedy",
          "Drama",
          "Romance",
          "School Life",
          "Shoujo",
          "Slice Of Life",
        ],
        author: "Taamo",
        rating: 4.5,
        likes: 1120,
        view: 1050,
      ),
      Anime(
        id: 8,
        title: "Masamune-kun no Revenge: Engagement",
        image:
            "https://i0.wp.com/komikstation.co/wp-content/uploads/2023/04/Masamune-kun-no-Revenge-Engagement.jpg",
        chapter: 5,
        status: "Ongoing",
        sinopsis:
            "Sudah satu tahun berlalu sejak Makabe Masamune dan Adagaki Aki bertemu...",
        release: "2023",
        genre: ["Comedy", "Romance"],
        author: "Takeoka Hazuki",
        rating: 4.0,
        likes: 750,
        view: 790,
      ),
      Anime(
        id: 9,
        title: "Osananajimi no Ohimesama",
        image:
            "https://i1.wp.com/komikstation.co/wp-content/uploads/2022/12/Osananajimi-no-Ohimesama.jpg",
        chapter: 47,
        status: "Completed",
        sinopsis:
            "Persahabatan vs. cinta...!? Komedi romantis cinta segitiga tentang terjebak di antara dua putri!!",
        release: "2023",
        genre: ["Comedy", "Romance", "Shounen"],
        author: "9'C",
        rating: 4.4,
        likes: 980,
        view: 950,
      ),
      Anime(
        id: 10,
        title: "Onnanoko wa Otoko no Tame no Kisekae Ningyouja Nenda yo",
        image:
            "https://i2.wp.com/komikstation.co/wp-content/uploads/2023/12/Onnanoko-wa-Otoko-no-Tame-no-Kisekae-Ningyouja-Nenda-yo-Vol-1.jpg",
        chapter: 10,
        status: "Ongoing",
        sinopsis:
            "I'm Not Some Man's Dress-Up-Doll!, Girls Are Not Dress-up Dolls for the Sake of Men",
        release: "2023",
        genre: ["Comedy", "Romance"],
        author: "Ziki Masaya",
        rating: 3.9,
        likes: 680,
        view: 720,
      ),
      Anime(
        id: 11,
        title: "Kekkon shiyou. Rikon zentei de",
        image:
            "https://i3.wp.com/komikstation.co/wp-content/uploads/2024/07/Kekkon-shiyou.-Rikon-zentei-de.-Vol-1.png",
        chapter: 2,
        status: "Ongoing",
        sinopsis:
            "Sebagai seorang NEET yang kini genap 30 tahun, Kyousuke di usir dari rumah orang tuanya...",
        release: "2023",
        genre: ["Comedy", "Josei", "Romance"],
        author: "Sakaguchi Azuma",
        rating: 4.2,
        likes: 820,
        view: 850,
      ),
      Anime(
        id: 12,
        title: "Exorcist wo Otosenai",
        image:
            "https://i2.wp.com/komikstation.co/wp-content/uploads/2022/07/Exorcist-wo-Otosenai.jpg",
        chapter: 44,
        status: "Ongoing",
        sinopsis:
            "Sebagai pengusir setan terkuat, seorang anak laki-laki yang dipilih oleh Tuhan terlibat dalam pertempuran mematikan dengan Raja Iblis...",
        release: "2021",
        genre: ["Comedy", "Romance", "Shounen", "Supernatural"],
        author: "Arima Aruma",
        rating: 4.3,
        likes: 890,
        view: 910,
      ),
      Anime(
        id: 13,
        title: "Plunderer",
        image:
            "https://i0.wp.com/komikstation.co/wp-content/uploads/2018/04/14405.jpg",
        chapter: 82,
        status: "Ongoing",
        sinopsis:
            "Tahun 305 Kalender Alcian, dan dunia saat ini dikendalikan oleh 'Numbers'...",
        release: "2014",
        genre: [
          "Action",
          "Adventure",
          "Comedy",
          "Drama",
          "Ecchi",
          "Romance",
          "Seinen",
          "Supernatural",
        ],
        author: "Minazuki Zuu",
        rating: 4.1,
        likes: 1050,
        view: 1100,
      ),
      Anime(
        id: 14,
        title: "Nidome no Jinsei wo Isekai de",
        image:
            "https://i0.wp.com/komikstation.co/wp-content/uploads/2018/02/Nidome-no-Jinsei-wo-Isekai-de.jpg",
        chapter: 49,
        status: "Ongoing",
        sinopsis:
            "Kunugi Renya merupakan sosok yang sudah tiada di usia tuanya yakni di umur 94 tahun...",
        release: "2016",
        genre: [
          "Action",
          "Adventure",
          "Comedy",
          "Drama",
          "Ecchi",
          "Fantasy",
          "Harem",
          "Isekai",
          "Romance",
          "Shounen",
        ],
        author: "Main",
        rating: 3.8,
        likes: 790,
        view: 830,
      ),
      Anime(
        id: 15,
        title: "Tower Dungeon",
        image:
            "https://i3.wp.com/komikstation.co/wp-content/uploads/2024/03/Tower-Dungeon-Vol-1.jpg",
        chapter: 16,
        status: "Ongoing",
        sinopsis:
            "Latarnya adalah kerajaan tertentu. Untuk menyelamatkan putri kerajaan yang di culik...",
        release: "2025",
        genre: [
          "Action",
          "Adventure",
          "Drama",
          "Fantasy",
          "Supernatural",
          "Shounen",
        ],
        author: "NIHEI Tsutomu",
        rating: 4.0,
        likes: 720,
        view: 780,
      ),
      Anime(
        id: 16,
        title: "Igyou Atama-san to Ningen-chan",
        image:
            "https://i0.wp.com/komikstation.co/wp-content/uploads/2025/01/Igyou-Atama-san-to-Ningen-chan-Vol-2.jpg",
        chapter: 24,
        status: "Ongoing",
        sinopsis:
            "Tokoh utama, yang bekerja keras sebagai budak perusahaan/Wanita kantoran di dunia manusia...",
        release: "2022",
        genre: ["Isekai", "Josei", "Romance", "Slice of life"],
        author: "Miketama",
        rating: 4.2,
        likes: 850,
        view: 880,
      ),
      Anime(
        id: 17,
        title: "Sekai Ni Hitori, Zenzokusei Mahou no Tsukaite",
        image:
            "https://i3.wp.com/komikstation.co/wp-content/uploads/2023/02/Sekai-ni-Hitori-Zenzokusei-Mahou-no-Tsukaite-Vol-1.jpg",
        chapter: 38,
        status: "Ongoing",
        sinopsis:
            "Setelah kecelakaan lalu lintas, Zenichi Kiyama, seorang pekerja kantoran yang rendah hati...",
        release: "2022",
        genre: ["Action", "Adventure", "Fantasy", "Seinen"],
        author: "Katanakaji",
        rating: 4.1,
        likes: 810,
        view: 840,
      ),
      Anime(
        id: 18,
        title: "Reincarnation no kaben",
        image:
            "https://i0.wp.com/komikstation.co/wp-content/uploads/2018/10/Reincarnation-no-Kaben-Vol-18.jpg",
        chapter: 66,
        status: "Ongoing",
        sinopsis:
            "Berusaha keras untuk menemukan bakatnya, Senji touya mencoba semua yang ia bisa agar bisa menemukan nya...",
        release: "2014",
        genre: [
          "Action",
          "Adventure",
          "Horror",
          "Pyschological",
          "Shounen",
          "Supernatural",
          "Tragedy",
        ],
        author: "KONISHI mikihisa",
        rating: 4.0,
        likes: 920,
        view: 950,
      ),
      Anime(
        id: 19,
        title: "Isekai de Slow Life wo (Ganbou)",
        image:
            "https://i1.wp.com/komikstation.co/wp-content/uploads/2022/01/Isekai-de-Slow-Life-wo-Ganbou.jpg",
        chapter: 51,
        status: "Ongoing",
        sinopsis:
            "Dengan kehendak sang dewi, Itsuki shinomiya diberi hak istimewa unutuk memilih berbagai kemampuan...",
        release: "2019",
        genre: ["Action", "Adventure", "Ecchi", "Harem", "Isekai", "Shounen"],
        author: "Shige",
        rating: 3.9,
        likes: 790,
        view: 820,
      ),
      Anime(
        id: 20,
        title:
            "Kage no jitsuryokusha ni Naritakute! Master of Garden : Shichikage Retsuden",
        image:
            "https://i1.wp.com/komikstation.co/wp-content/uploads/2024/06/Kage-no-Jitsuryokusha-ni-Naritakute-Master-of-Garden-Shichikage-Retsuden.jpg",
        chapter: 9,
        status: "Ongoing",
        sinopsis:
            "Cid Kaguenou, seorang anak laki laki yang menikmati setting The Eminence in Shadow di dunia yang berbeda...",
        release: "2024",
        genre: [
          "Action",
          "Adventure",
          "Comedy",
          "Fantasy",
          "Harem",
          "Isekai",
          "Shounen",
        ],
        author: "AIZAWA daisuke",
        rating: 4.3,
        likes: 880,
        view: 910,
      ),
    ];
  }
}
